### PR TITLE
Added "Open at startup" option

### LINKED ISSUE #65: Run at startup
Add option in setting to automatically run gitify at startup.

### PR DESCRIPTION
**Pull request by sergiovilar**
Closes #65 .

### CODE REVIEW

**Comment by ekonstantinidis** [comment]
That looks really nice @sergiovilar ! Will give it a try ASAP and let you know how it goes! Can you also fix the test coverage? If not, I can give it a go!

**Comment by sergiovilar** [comment]
Hi @ekonstantinidis, thanks! I fixed in the last commit, it's all passing as you can see [here](https://travis-ci.org/ekonstantinidis/gitify/builds/72398567).

**Comment by ekonstantinidis** [comment]
While it seems to work (it does open when the mac starts), it seems that when you toggle the setting("Open at start up") the UI crashes. To reproduce just toggle that setting and then press the back button - for me it doesn't go back. Will have a further look too!

**Comment by sergiovilar** [comment]
@ekonstantinidis I'll take a look!

**Comment by sergiovilar** [comment]
@ekonstantinidis now seems to be working fine! Please take a look :smile:

**Comment by ekonstantinidis** [comment]
@sergiovilar Works niiice! Merged & thanks! :rocket: :rocket: :rocket:

**Comment by sergiovilar** [comment]
:grin:

**Pull request merged**
