### PR TITLE
Cross gitify

### PR DESCRIPTION
**Pull request by mrmlnc**
### Changelog:

  * Update dependencies
  * Add EditorConfig
  * Correct determining of the position
  * Pretty code
  * Support Windows & Linux

### Tested:

  * Windows 10 (all taskbar positions: bottom, top, left and right)
  * Linux Mint XFCE (top and bottom)
  * Linux Manjaro XFCE (bottom, top, left and right)
  * Ubuntu 14LTS (requires `libappindicator1`, but works)

Please test on OS X and let me know if it works.

### Not tested:

**Auto-update**

They say that now works on OS X and [Windows with Squirrel](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md#windows) but I disabled it for Windows. 

If just set version to `0.1.17` and check updates on Windows, then:
```
ERRORED.
Event: {}. MESSAGE: Can not find Squirrel
```

**Auto-launch**

Windows complains on:
```js
process.execPath.match(/.*?\.app/)[0]
```

I removed [0]. OS X requires it?

### CODE REVIEW

**Comment by mrmlnc** [comment]
Ooops, new `jest-cli` requires Node.js >=4 :(

**Comment by ekonstantinidis** [comment]
That looks awesome @mrmlnc ! Can't wait to give it a go! :star2:

**Comment by ekonstantinidis** [comment]
It looks like Windows - Auto Update was just released :yum: Would you like to have a look if it's easy to implement autoupdate for Windows too? http://blog.atom.io/2015/11/05/electron-updates-mac-app-store-and-windows-auto-updater.html

**Comment by mrmlnc** [comment]
XO-XO :octopus: :tada: 

image

Well, I'll think about this tomorrow. At first it seems that there is nothing complicated here :)

**Comment by mrmlnc** [comment]
How to check the work of the auto-update?

**Comment by mrmlnc** [comment]
@ekonstantinidis The server-side setup for Windows Squirrel is also different from OS X. I don't know how to work with that. Wait https://github.com/jenslind/electron-gh-releases/issues/4

**Comment by ekonstantinidis** [comment]
Yes you're right! We can leave Windows - Auto Update for later I guess! :+1:

**Comment by mrmlnc** [comment]
Maybe can use a custom solution, such as

https://github.com/Aluxian/electron-superkit

**Comment by vicentedealencar** [comment]
Hi, right now I am starring at a `Can not find Squirrel` error message so I found this issue, did you solved this one yet?

 > The server-side setup for Windows Squirrel is also different from OS X. I don't know how to work with that.

serve the releases folder as static files and it just works

**Comment by ekonstantinidis** [comment]
Hello there! Sorry for the late reply - I've been super busy! So I spent the last couple of days trying to bring the whole project up to date, updating to react `0.14.3`, react-router `1.0.1`, jest to `0.8.0`, **electron** to `0.35.2` and pretty much all the dependencies.. Also had to fix the completely broken tests because of react 0.14's context etc.

So part of this PR is already merged - but haven't merged the windows & linux support yet. Thought I should let you know since there are some breaking changes in `master` now :)

**Pull request merged**
