### PR TITLE
Prepare Linux

### PR DESCRIPTION
**Pull request by ekonstantinidis**
Continues #41.

### CODE REVIEW

**Comment by sergiovilar** [comment]
Great! We'll need a workflow to distribute the version for ubuntu. I suggest create a .deb on Travis but where we can host? Maybe there's a way to host on github releases?

**Comment by ekonstantinidis** [comment]
@sergiovilar Well since this is an electron app, I guess we can move the discussion to slack (atom team - http://atom-slack.herokuapp.com/)? My username is ekonstantinidis. See you there!

**Comment by Trozz** [comment]
@sergiovilar we could possibly use a PPA or possibly look at hosting the deb on github as a [release](https://help.github.com/articles/creating-releases/)

**Comment by ekonstantinidis** [comment]
Just a note: For Ubuntu 14 you have to install `libappindicator1` for the tray icon to show up([more info](http://electron.atom.io/docs/v0.34.0/api/tray/#tray)).

    sudo apt-get install libappindicator1

**Comment by ekonstantinidis** [comment]
I'm closing this one in favour for #119 .

**Pull request closed without merging**
